app_name: AppExample 
app_filename: AppExample.zip # Should match exactly the .zip file found in ./release/
s3_bucket_name: app-example-distribution # Must be unique

# More variables need to be added to your environment. See the readme
